### ISSUE TITLE
About the NPM package name

### ISSUE THREAD

**Issue by nag** [mambaz/string-case#1]
Hey @mambaz!

I already emailed you about this a few days ago, but thought I'd contact you here too, in case you don't read your email that often. If I'm wrong, I apologize for bothering you again. Just wondering if you could release the package name `string-case` if you don't need it anymore.

(As far as I know, all you have to do is force unpublish)
```
npm unpublish string-case --force
```

Thanks anyway! ❤

**Comment by mambaz** [comment]
Hi, may I know the issue of this current version? Sorry I cannot unpublished this package name.
